### ISSUE TITLE
When duplicating a page or exporting, children of other boxes are not exported

### ISSUE THREAD

**Issue by elisandroesp** [OFFLINE-GmbH/oc-boxes-support#86]
**Describe the bug**
When duplicating a page or exporting, only the first level of content is duplicated/exported, losing content

**Boxes Version**
v3.1.17

**To Reproduce**
1. Create a page (Page1) with a 'columns' component and add a couple children to this box
2. Duplicate the page
3. Go to the duplicated page (Page2)
4. See it only holds the 'columns' component, nothing inside it.

The same happens when you export this content, only the first level is exported.

**Code**
columns.yaml
```
handle: container-columns
name: Columns
section: Layout
children: true
spacing:
  - general

form:
  tabs:
    defaultTab: Content
    fields:

      columns:
        label: Number Of columns
        type: dropdown
        default: two
        options:
          one: 1
          two: 2
          three: 3
          four: 4

      anchors-mixin:
        type: mixin
```
columns.htm
```

<div
  class="
    bx--columns
    bx--columns--{{ box.columns }}
  "
  id="{{ box.anchor_id ? box.anchor_id : '' }}"
  data-boxes-container
>
    {% for child in box.children %}
        <div class="bx--columns__item">
            {{ child.renderMergeContext(context, { loop: loop, isChildren: true }) | raw }}
        </div>
    {% endfor %}
</div>

```
**Screenshots**

**Additional context**
WE LOVE Boxes!!!

**Comment by elisandroesp** [comment]
This data loss problem is preventing us from deploying the Boxes solution. Can we help it somehow?

**Comment by tobias-kuendig** [comment]
Thank you for the report! Please try again using v3.1.18. Duplication should be fixed now.

Regarding exporting: Be aware that this feature is currently pretty unstable. For production use-cases I suggest you export the database manually. We will provide an update soon that fixes the export logic. 

The additional support for the multisite and revision features have added a ton of complexity that the export feature has to properly retrofit.

**Comment by elisandroesp** [comment]
Hi, thanks for the explanation! We'll not use it until the component is fixed, thanks!

**Comment by kevin-invato** [comment]
Hi Tobias,

It seems that the bug is still here. It happens mostly when the revisions functionality is active.

How to reproduce:

1. Build a page with boxes containing child boxes
2. Duplicate the page
3. Child boxes are gone for visitors, parent box is still there
4. When adding new child boxes to the parent box, the new child boxes still aren't visible for visitors. (logged-in back-end users can see the child boxes)

Could you look into this?

Thanks in advance!
- Kevin
-

**Comment by tobias-kuendig** [comment]
Can you give the latest version a try? I did release an update for this issue yesterday.

**Comment by kevin-invato** [comment]
It's fixed, thank you very much!
